language: python
python:
  - "2.7"

# Install Python dependencies (required for running tests)
install: pip install -r requirements.txt

# Discover and run all plugin tests
script: python -m unittest discover

# Build and Deploy a new plugin ZIP bundle
after_success:
- bash after_success.sh